#!/bin/bash

echo "📋 InfluxDB 토큰 확인 방법"
echo "=========================="
echo ""
echo "🔧 방법 1: 컨테이너에서 직접 확인"
echo "docker-compose exec influxdb influx auth list"
echo ""
echo "🔧 방법 2: InfluxDB UI에서 확인"
echo "1. http://localhost:8086 접속"
echo "2. admin/adminpassword로 로그인" 
echo "3. Data > API Tokens 메뉴에서 토큰 확인"
echo ""
echo "🔧 방법 3: 컨테이너 로그에서 확인"
echo "docker-compose logs influxdb | grep -i token"
echo ""
echo "💡 현재 설정된 기본 토큰:"
echo "my-super-secret-crypto-tracker-token-12345"
echo ""
echo "⚠️  보안상 실제 운영환경에서는 반드시 토큰을 변경하세요!"